### ISSUE TITLE
Switch from HTTP server to internal IPC

### ISSUE THREAD

**Issue by jarradh** [status-im/status-go#134]
Now things are 'working', we can consider a switch to an internal IPC for the node on the device, this will fix the API unavailability on node restart on Android, improve battery life and secure the node from other apps on the device.

**Comment by farazdagi** [comment]
We already have IPC support, one just needs to pass two extra configuration variables:
```yaml
{
    "IPCFile": "geth.ipc", # relative to DataDir
    "IPCEnabled": true, # false by default
}
```

Now, the only thing I can add, is `HTTPEnabled` flag, so that HTTP server is not started (right now IPC or WS are started *alongside* the running HTTP server)?
